
# dataset:
#   name: paired-lensing  # paired-lensing is currently the only name
#   data_dir: D:\Datasets\2023_strong_lensing_data_set\data_set  # path/to/the/dataset
#   subset_size: null

model: 
  name: simsiam
  backbone: vit-base  # vit-base, resnet50, resnet18
  file: D:\Projects\2023_simsiam_vit_lensing\20230420_100k_eff_batch_size_400_models\100k_eff_batch_size_400\DP\simsiam-lensing_0411102733_loss_-0.9243.pt  # provide the model path 

train:
  batch_size: 20

