name: umap  # name it however you like

umap:
  n_neighbors: 15  # default to 15

dataset:
  name: paired-lensing  # paired-lensing is currently the only name
  data_dir: D:\Datasets\2023_strong_lensing_data_set\data_set  # path/to/the/dataset
  subset_size: null

model:
  name: simsiam  # simsiam or eccv_2022
  backbone: vit-base  # only used if name == simsiam, e.g. vit-base, resnet50, resnet18, etc. 
  file: D:\Projects\2023_simsiam_vit_lensing\20230503_icml_models\100k_lr_0.01\DP\ViT_bsize_400\simsiam-lensing_0428121241_loss_-0.9232.pt  # provide the model path 

train:
  batch_size: 20

testsets:
  STL10:
    root: D:\Datasets
    split: unlabeled
    subset_size: 1000
  Lens2022:
    root: D:\Datasets\2022_icml_lens_sim\geoff_1200
    subset_size: 1000
  RealHST:
    root: D:\Datasets\2023_hst_lensed_quasars\npy_files
    suffix: cutout
    subset_size: null

aug_method: lensiam